import argparse
import cmd
from os import PathLike
from pprint import pprint
import shutil
import tempfile
from pathlib import Path
import textwrap

from modflow_devtools.dfn2toml import convert as dfn2toml
from modflow_devtools.download import download_and_unzip
import yaml

from codegen import make_all





_PROJ_ROOT_PATH = Path(__file__).parents[2].expanduser().resolve().absolute()
_DEFAULT_DFNS_PATH = Path(__file__).parents[1] / "dfns.txt"
DFN_PATH = _PROJ_ROOT_PATH / "doc" / "mf6io" / "mf6ivar" / "dfn"
_IDM_MODULE_PATH = _PROJ_ROOT_PATH / "src" / "Idm"
_MF6_REPO_OWNER = "MODFLOW-ORG"
_MF6_REPO_NAME = "modflow6"
_CMD = cmd.Cmd()  # for pretty printing



def generate_classes(dfnpath: PathLike, verbose=False):
    """
    Generate Python classes for MODFLOW 6 using definition files fetched
    from the MODFLOW 6 repository or available on the local filesystem.

    Parameters
    ----------
    owner : str, default "MODFLOW-ORG"
        Owner of the MODFLOW 6 repository to use to update the definition
        files and generate the MODFLOW 6 classes.
    repo : str, default "modflow6"
        Name of the MODFLOW 6 repository to use to update the definition.
    ref : str, default "master"
        Branch name, tag, or commit hash to use to update the definition.
    dfnpath : str
        Path to a definition file folder that will be used to generate the
        MODFLOW 6 classes.  Default is none, which means that the ref (and
        owner/repo) will be used instead. If dfnpath is specified, it will
        take precedence.
    """

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        if dfnpath is not None:
            dfnpath = Path(dfnpath).expanduser().resolve().absolute()
            if not dfnpath.is_dir():
                raise FileNotFoundError(
                    f"Specified DFN path '{dfnpath}' does not exist or is not a directory."
                )

        if verbose:
            dfns = list(dfnpath.glob("*.dfn"))
            module_name = ".".join(_IDM_MODULE_PATH.relative_to(_PROJ_ROOT_PATH).parts)
            print(
                f"Generating module {module_name} from {len(dfns)} DFNs in: {dfnpath}"
            )
            print()
            _CMD.columnize([f.name for f in dfns])
            print()

        tomlpath = dfnpath / "toml"
        tomlpath.mkdir(exist_ok=True)
        dfn2toml(dfnpath, tomlpath)
        shutil.rmtree(_IDM_MODULE_PATH)
        _IDM_MODULE_PATH.mkdir(parents=True)
        make_all(tomlpath, _IDM_MODULE_PATH, version=2, legacydir=dfnpath)
        if verbose:
            files = list(_IDM_MODULE_PATH.glob("*.f90"))
            print(f"Generated {len(files)} module files in: {_IDM_MODULE_PATH}")
            print()
            _CMD.columnize([f.name for f in files])
            print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Convert DFN files to Fortran source files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            Generate Fortran source code from DFN files. This script
            converts definition (DFN) files to Fortran source files,
            each representing a parameter set for a particular input
            definition. Fortran files generated by this tool provide
            support for simulations, models or packages described by
            the given DFN files. Each DFN file is transformed into a
            corresponding Fortran file with "idm" and the same stem:
            e.g. gwf-ic.dfn becomes gwf-icidm.f90.
            """
        ),
    )
    parser.add_argument(
        "-d",
        "--dfn",
        required=False,
        default=_DEFAULT_DFNS_PATH,
        help="Path to a DFN file, a directory containing DFN files, or to a text or YAML file listing DFN files (one per line)",
    )
    parser.add_argument(
        "-o",
        "--outdir",
        required=False,
        default=_IDM_MODULE_PATH,
        help="The directory to write Fortran source files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        required=False,
        default=False,
        help="Whether to show verbose output",
    )
    args = parser.parse_args()
    dfn = Path(args.dfn)
    outdir = Path(args.outdir) if args.outdir else Path.cwd()
    verbose = args.verbose

    if dfn.suffix.lower() in [".txt"]:
        dfns = open(dfn, "r").readlines()
        dfns = [l.strip() for l in dfns]
        dfns = [l for l in dfns if not l.startswith("#") and l.lower().endswith(".dfn")]
        if dfn == _DEFAULT_DFNS_PATH:
            dfns = [DFN_PATH / p for p in dfns]
    elif dfn.suffix.lower() in [".yml", ".yaml"]:
        dfns = yaml.safe_load(open(dfn, "r"))
    elif dfn.suffix.lower() in [".dfn"]:
        dfns = [dfn]

    assert all(p.is_file() for p in dfns), (
        f"DFNs not found: {[p for p in dfns if not p.is_file()]}"
    )

    try:
        generate_classes(**args)
    except (EOFError, KeyboardInterrupt):
        sys.exit(f" cancelling '{sys.argv[0]}'")


if __name__ == "__main__":
    """Run command-line with: python -m flopy.mf6.utils.generate_classes"""
    cli_main()

    